//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Pilkarzyki_DBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public Players()
        {
            this.Teams = new HashSet<Teams>();
            this.Teams1 = new HashSet<Teams>();
        }
    
        public int PlayerID { get; set; }
        public string Nickname { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<Teams> Teams { get; set; }
        public virtual ICollection<Teams> Teams1 { get; set; }
    }
}
