//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Pilkarzyki_DBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scores
    {
        public int ScoreID { get; set; }
        public int FirstTeamID { get; set; }
        public int SecondTeamID { get; set; }
        public int FirstTeamScore { get; set; }
        public int SecondTeamScore { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Teams Teams { get; set; }
        public virtual Teams Teams1 { get; set; }
    }
}
