//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Pilkarzyki_DBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams
    {
        public Teams()
        {
            this.Scores = new HashSet<Scores>();
            this.Scores1 = new HashSet<Scores>();
        }
    
        public int TeamID { get; set; }
        public int GoalKeeperID { get; set; }
        public int AttackerID { get; set; }
        public string TeamName { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Players Players { get; set; }
        public virtual Players Players1 { get; set; }
        public virtual ICollection<Scores> Scores { get; set; }
        public virtual ICollection<Scores> Scores1 { get; set; }
    }
}
