//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Pilkarzyki_DBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PlayerWinsStats
    {
        public int PlayerID { get; set; }
        public string WinnerName { get; set; }
        public Nullable<int> WinsCount { get; set; }
        public Nullable<int> GamesPlayed { get; set; }
        public Nullable<int> WinsPercentage { get; set; }
    }
}
