//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Pilkarzyki_DBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_TeamWinsStats
    {
        public int TeamID { get; set; }
        public string WinningTeamName { get; set; }
        public Nullable<int> WinsCount { get; set; }
        public Nullable<int> PlayedGamesCount { get; set; }
        public Nullable<int> PercentageOfWins { get; set; }
    }
}
